// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAExCNanTDh2GDMLh11CTj2GLemNH5yFBU',
    appId: '1:907796239054:web:da046bffa588ba8bbd769f',
    messagingSenderId: '907796239054',
    projectId: 'telegram-clone-2905c',
    authDomain: 'telegram-clone-2905c.firebaseapp.com',
    storageBucket: 'telegram-clone-2905c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGUhr1OY0RkBVfHUDElSwTXwAZxoDsWKw',
    appId: '1:907796239054:android:3a9f4d9b9184f008bd769f',
    messagingSenderId: '907796239054',
    projectId: 'telegram-clone-2905c',
    storageBucket: 'telegram-clone-2905c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4Jl6zs3fCc3-M0qlysEcSrRgEWweVJbk',
    appId: '1:907796239054:ios:f544322029cb67d2bd769f',
    messagingSenderId: '907796239054',
    projectId: 'telegram-clone-2905c',
    storageBucket: 'telegram-clone-2905c.firebasestorage.app',
    iosBundleId: 'com.example.telegramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4Jl6zs3fCc3-M0qlysEcSrRgEWweVJbk',
    appId: '1:907796239054:ios:f544322029cb67d2bd769f',
    messagingSenderId: '907796239054',
    projectId: 'telegram-clone-2905c',
    storageBucket: 'telegram-clone-2905c.firebasestorage.app',
    iosBundleId: 'com.example.telegramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAExCNanTDh2GDMLh11CTj2GLemNH5yFBU',
    appId: '1:907796239054:web:3e2927d5330130e2bd769f',
    messagingSenderId: '907796239054',
    projectId: 'telegram-clone-2905c',
    authDomain: 'telegram-clone-2905c.firebaseapp.com',
    storageBucket: 'telegram-clone-2905c.firebasestorage.app',
  );
}
